# Configuration: SED.main.config.ndf.yaml
Instrument:
  Cameras:
    Andor:
      DC: 0.0004
      RN: 4
      readtime: 82
    E2V:
      DC: 0.006
      RN: 3.3
      readtime: 37
    PI:
      DC: 0.006
      RN: 5.0
      readtime: 37
    Selected: PI
  Lenslets:
    radius: 0.00245
    rotation: 27.0
  PSF:
    ellipse: true
    size:
      px: 2.4
    stdev:
      px: 1.0
  Scatter:
    Amplifier: 0.1
    Kernels:
      A:
        mag: 0.0008
        stdev: 16.7
        type: Gaussian
      B:
        mag: 7.0e-05
        stdev: 55.5
        type: Gaussian
      C:
        mag: 7.0e-06
        stdev: 222
        type: Gaussian
  Tel:
    area: 16417.8
    obsc:
      px: 0.2
      ratio: 0.2
    radius:
      px: 1.2
  Thpt:
    File: thpt.npy
    Type: prism_pi
  camera: PI
  ccd:
    size:
      px: 2048
  convert:
    pxtomm: 0.0135
  eADU: 0.03802
  files:
    dispersion: dispersion.dat
    encircledenergy: encircled_energy.dat
    lenslets: rays.dat
  image:
    size:
      mm: 40.0
  wavelengths:
    max: 9.2e-07
    min: 3.7e-07
    resolution: 100
Observation:
  Background:
    Atmosphere: Atmosph
    Files:
      PalSky:
        Amplifier: 0.1
        Filename: palsky_100318.dat
    Sky: PalSky
  Moon:
    Phase: 0.45
  airmass: 1
  exposure: 1200
  number: 3
Source:
  CubeName: CUBE.fits
  Filename: SNIa.R1000.dat
  Lines:
    List: Lines.dat
    sigma: 1.0e-08
    value: 100000000.0
  PXSize:
    mm: 0.005
  Rotation: 0.7853981633974483